# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\endgame.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_endGame(object):
    def setupUi(self, endGame):
        endGame.setObjectName("endGame")
        endGame.resize(319, 280)
        endGame.setMaximumSize(QtCore.QSize(319, 280))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\files/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        endGame.setWindowIcon(icon)
        endGame.setStyleSheet("background-color: rgb(159, 62, 213);\n"
"color: rgb(255, 64, 64);")
        self.centralwidget = QtWidgets.QWidget(endGame)
        self.centralwidget.setObjectName("centralwidget")
        self.endLabel = QtWidgets.QLabel(self.centralwidget)
        self.endLabel.setGeometry(QtCore.QRect(6, 2, 301, 171))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(32)
        self.endLabel.setFont(font)
        self.endLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.endLabel.setWordWrap(True)
        self.endLabel.setObjectName("endLabel")
        self.newGameButton = QtWidgets.QPushButton(self.centralwidget)
        self.newGameButton.setGeometry(QtCore.QRect(50, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.newGameButton.setFont(font)
        self.newGameButton.setStyleSheet("background-color: rgb(163, 239, 9);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.newGameButton.setObjectName("newGameButton")
        self.quitGameButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitGameButton.setGeometry(QtCore.QRect(180, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quitGameButton.setFont(font)
        self.quitGameButton.setStyleSheet("background-color: rgb(255, 39, 39);\n"
"color: rgb(255, 255, 255);")
        self.quitGameButton.setObjectName("quitGameButton")
        endGame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(endGame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 319, 21))
        self.menubar.setObjectName("menubar")
        endGame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(endGame)
        self.statusbar.setObjectName("statusbar")
        endGame.setStatusBar(self.statusbar)

        self.retranslateUi(endGame)
        QtCore.QMetaObject.connectSlotsByName(endGame)

    def retranslateUi(self, endGame):
        _translate = QtCore.QCoreApplication.translate
        endGame.setWindowTitle(_translate("endGame", "Questions"))
        self.endLabel.setText(_translate("endGame", "End of Game"))
        self.newGameButton.setText(_translate("endGame", "New game"))
        self.quitGameButton.setText(_translate("endGame", "Quit"))
