# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\homescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeScreen(object):
    def setupUi(self, HomeScreen):
        HomeScreen.setObjectName("HomeScreen")
        HomeScreen.resize(320, 288)
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        HomeScreen.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\files/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HomeScreen.setWindowIcon(icon)
        HomeScreen.setStyleSheet("background-color: rgb(159, 62, 213);")
        self.playButton = QtWidgets.QPushButton(HomeScreen)
        self.playButton.setGeometry(QtCore.QRect(100, 140, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(14)
        self.playButton.setFont(font)
        self.playButton.setStyleSheet("background-color: rgb(40, 168, 88);\n"
"border-color: rgb(85, 255, 0);\n"
"color: rgb(230, 236, 215);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.176136 rgba(201, 247, 111, 255), stop:0.477273 rgba(185, 247, 62, 255), stop:0.926136 rgba(159, 238, 0, 255));")
        self.playButton.setObjectName("playButton")
        self.rulesButton = QtWidgets.QPushButton(HomeScreen)
        self.rulesButton.setGeometry(QtCore.QRect(100, 210, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(14)
        self.rulesButton.setFont(font)
        self.rulesButton.setStyleSheet("background-color: rgb(40, 168, 88);\n"
"color: rgb(230, 236, 215);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.238636 rgba(255, 115, 115, 255), stop:0.556818 rgba(255, 64, 64, 255), stop:1 rgba(255, 0, 0, 255));")
        self.rulesButton.setObjectName("rulesButton")
        self.logo = QtWidgets.QLabel(HomeScreen)
        self.logo.setGeometry(QtCore.QRect(0, 0, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.logo.setFont(font)
        self.logo.setStyleSheet("color: rgb(255, 64, 64);")
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.usernameLabel = QtWidgets.QLabel(HomeScreen)
        self.usernameLabel.setGeometry(QtCore.QRect(10, 80, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameField = QtWidgets.QLineEdit(HomeScreen)
        self.usernameField.setGeometry(QtCore.QRect(70, 80, 161, 20))
        self.usernameField.setObjectName("usernameField")
        self.userError = QtWidgets.QLabel(HomeScreen)
        self.userError.setGeometry(QtCore.QRect(80, 100, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userError.setFont(font)
        self.userError.setStyleSheet("color: rgb(255, 0, 0);")
        self.userError.setText("")
        self.userError.setWordWrap(True)
        self.userError.setObjectName("userError")

        self.retranslateUi(HomeScreen)
        QtCore.QMetaObject.connectSlotsByName(HomeScreen)

    def retranslateUi(self, HomeScreen):
        _translate = QtCore.QCoreApplication.translate
        HomeScreen.setWindowTitle(_translate("HomeScreen", "Form"))
        self.playButton.setText(_translate("HomeScreen", "PLAY"))
        self.rulesButton.setText(_translate("HomeScreen", "RULES"))
        self.logo.setText(_translate("HomeScreen", "QUESTIONS?"))
        self.usernameLabel.setText(_translate("HomeScreen", "Username:"))
